### ISSUE TITLE
load.sentinel1 error

### ISSUE THREAD

**Issue by natasnat** [birgander2/PyRAT#30]
It is currently not possible to upload Sentinel-1 scenes. 

In GUI mode I get the error POLARISATION' KeyError in Spaceborne_GDAL.py (line 241). 

On the the command line I get ERROR: manifest.save file not found! ERROR: 'bool' object is not iterable TypeError in LayerData.py (line 44). 

But my S1 SAFE folder has the manifest.save file and as I see it, PyRAT only needs {'dir': '', 'swath': 1}.
In debug mode:

 SENTINEL-1 IMPORT  {'dir': '', 'swath': 1}
  ERROR: manifest.save file not found!
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/PyRAT/PyRAT/pyrat/load/Spaceborne_GDAL.py", line 256, in sentinel1
    return Sentinel1(*args, **kwargs).run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PyRAT/PyRAT/pyrat/Worker.py", line 83, in run
    self.crash_handler(ex)
  File "/home/PyRAT/PyRAT/pyrat/Worker.py", line 527, in crash_handler
    raise ex
  File "/home/PyRAT/PyRAT/pyrat/Worker.py", line 80, in run
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PyRAT/PyRAT/pyrat/ImportWorker.py", line 37, in main
    newlayer = pyrat.data.addLayer(array=data, block=self.block)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PyRAT/PyRAT/pyrat/LayerData.py", line 44, in addLayer
    for arr in array:  # Loop over all arrays in list
               ^^^^^
TypeError: 'bool' object is not iterable

**Comment by birgander2** [comment]
Sorry for being so slow. I checked that module and indeed there is a bug, but I don't get those errors!? Anyway, there was a problem of gdal switching apparently the key from "POLARISATION" to "POLARIZATION". This is fixed now. Can you please try again if it works now?

**Comment by natasnat** [comment]
Hi, I've tried it but it still doesn't work. I get the error:

SENTINEL-1 IMPORT  {'dir': '', 'swath': 1}
  ERROR: manifest.save file not found!
  
  ERROR : 'bool' object is not iterable
  TypeError in LayerData.py (line 44)

**Comment by birgander2** [comment]
Thanks for testing! The error you get now is pretty clear: "manifest.save file not found". This file should be (to my knowledge) always part of the dataset directory - it contains all the meta data. Are you sure that you have a complete product? From where did you get the data?

In any case, there is little I can do here, because we use the GDAL library for reading Sentinel-1 data, and obviously it seems to require this file. You can, however, try to read directly the geotiff files somewhere hidden in the product directory. But I'm not sure if this will give reasonable results.

**Comment by natasnat** [comment]
Yes, I am sure. I see the file manifest.save in the directory, but PyRAT cannot open it.  I get the data from Alaska Satellite Facility.

**Comment by birgander2** [comment]
The current code expects the manifest.save file to be located in the main product directory (e.g. S1A_xxxx/manifest.save). The error you get should occur if the file is not there (or has length zero). Can you post me a directory listing of your product? Something seems to be different.

**Comment by natasnat** [comment]
This is strange, the manifest.save is in the main product directory (e.g. S1A_xxxx/manifest.save). I have checked that the manifest.save is not empty.

Here is an S-1 scene I tried to load in PyRAT to download as a link (I downloaded it from the Alaska Satelite Facility):  https://upload.uni-jena.de/data/678f6523c28df5.75658275/S1A_IW_SLC__1SDV_20230829T054229_20230829T054257_050086_0606E8_2431.zip

Thanks!

**Comment by birgander2** [comment]
I have no problems (except that only the VH channels loads...)
```
>>> load.sentinel1(dir='/ste/usr/reigber/HR-L00034/Data/Sentinel-1/S1A_IW_SLC__1SDV_20230829T054229_20230829T054257_050086_0606E8_2431.SAFE/')
INFO: SENTINEL-1 IMPORT  {'dir': '/ste/usr/reigber/HR-L00034/Data/Sentinel-1/S1A_IW_SLC__1SDV_20230829T054229_20230829T054257_050086_0606E8_2431.SAFE/', 'swath': 1}
DEBUG: Creating disc layer /L1 = float32 (13572, 22935)
DEBUG: Creating converter from 5 to 3
DEBUG: Creating converter from 3 to 5
INFO: Activating /L1
'/L1'
>>> show()
```

**Comment by natasnat** [comment]
>>> load.sentinel1(dir='F:/usr/PyRAT/test_data/S1A_IW_SLC__1SDV_20230829T054229_20230829T054257_050086_0606E8_2431.SAFE/')
   SENTINEL-1 IMPORT  {'dir': 'F:/usr/PyRAT/test_data/S1A_IW_SLC__1SDV_20230829T054229_20230829T054257_050086_0606E8_2431.SAFE/', 'swath': 1}

[91m   ERROR : 'POLARISATION'
   KeyError in Spaceborne_GDAL.py (line 241)[0m


Am I doing something wrong?

**Comment by birgander2** [comment]
Ok, this looks at least different and the manifest.save file seems to be found. I get the impression that both "POLARIZATION" and "POLARISATION" is used as a key (I changed that)? Strange. Needs another fix, and I'll try to get the missing channel, too.

In any case, don't expect too much for IWS data. This reader is very basic and does not mosaic neither bursts nor swaths.

**Comment by natasnat** [comment]
Alright, thank you anyway!
